shared: &shared
  adapter: postgresql
  encoding: unicode

localaccess: &localaccess
  username: samuelrichardson
  password:

development:
  <<: *localaccess
  <<: *shared
  database: WebMProcessor_development

test:
  <<: *localaccess
  <<: *shared
  database: WebMProcessor_test

production:
  <<: *shared