shared: &shared
  adapter: mysql
  encoding: utf8

development:
  <<: *shared
  username: <%= ENV['DEVELOPMENT_DATABASE_USER'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] %>

test:
  <<: *shared
  username: <%= ENV['TEST_DATABASE_USER'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  host: <%= ENV['TEST_DATABASE_HOST'] %>

production:
  <<: *shared