shared: &shared
  adapter: mysql
  encoding: utf8

development:
  <<: *shared
  username: root
  password:
  database: WebMProcessor_development
  host: localhost

test:
  <<: *shared
  username: root
  password:
  database: WebMProcessor_test
  host: localhost