shared: &shared
  adapter: mysql

localaccess: &localaccess
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *localaccess
  <<: *shared
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *localaccess
  <<: *shared
  database: <%= ENV['DATABASE_NAME'] %>

production:
  <<: *shared