class Api::V1::SettingsController < ApplicationController
	respond_to :json

	def index
		@settings = {
			MIN_FRAME_RATE: ENV['MIN_FRAME_RATE'],
			MAX_FRAME_RATE: ENV['MAX_FRAME_RATE'],
			MIN_BIT_RATE: ENV['MIN_BIT_RATE'],
			MAX_BIT_RATE: ENV['MAX_BIT_RATE'],
			MIN_BUFFER_SIZE: ENV['MIN_BUFFER_SIZE'],
			MAX_BUFFER_SIZE: ENV['MAX_BUFFER_SIZE'],
			MIN_BIT_RATE_TOLERANCE: ENV['MIN_BIT_RATE_TOLERANCE'],
			MAX_BIT_RATE_TOLERANCE: ENV['MAX_BIT_RATE_TOLERANCE'],
			MIN_KEYFRAME_INTERVAL: ENV['MIN_KEYFRAME_INTERVAL'],
			MAX_KEYFRAME_INTERVAL: ENV['MAX_KEYFRAME_INTERVAL'],
			MIN_DURATION: ENV['MIN_DURATION'],
			MAX_DURATION: ENV['MAX_DURATION'],
			FIREBASE_URI: ENV['FIREBASE_URI'],
			RESOLUTIONS: eval(ENV['RESOLUTIONS'])
		}

		puts ENV['RESOLUTIONS']

		respond_with @settings
	end

end